### PR TITLE
Hexagon puzzle work

### PR DESCRIPTION
**Pull request by yazeedMohi**

### CODE REVIEW

**Comment by nathansttt** [comment]
Can you remove the .DS_Store files from the commit? They aren't needed, but are conflicting. (They are in my .gitignore file, but obviously haven't completely been ignored.) If you can remove the other conflicting file (Hexagon.xcscheme) we can merge that on its own, instead of handling it with the other large commit.

**Comment by yazeedMohi** [comment]
Alright I removed both .DS_Store files and recovered the old xcsheme file which we can update later as you mentioned.

**Comment by nathansttt** [comment]
@yazeedMohi Can you check the build logs above? Your commit is failing the build stage.

**Comment by nathansttt** [comment]
Given our conversation I will merge this and see what is causing the compile issues.

**Pull request merged**
